on: [push, pull_request]

name: Build

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.0.100-preview9-014004'

    - name: Define Version
      run: "export VERSION=$(git describe --long --tags --match 'v*' | sed 's/v//' | sed -E 's/[-].+//g')"

    - name: Build
      run: echo $VERSION && dotnet build --configuration Release src /p:Version=$VERSION

    - name: Test
      run: dotnet test --configuration Release src
