on: [push]

name: .NET Core

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.0.100-preview9-014004'

    - name: Build with dotnet
      run: dotnet build --configuration Release
